### PR TITLE
Work-in-progress to discuss

### PR DESCRIPTION
**Pull request by abollini**

### CODE REVIEW

**Comment by mspalti** [comment]
@abollini , I'll update my pull request tomorrow with some comments and corrections. I also reviewed this PR and will make a few code comments now.

**Comment by mspalti** [comment]
If I understand correctly, the multi-volume book will create multiple sequences in the manifest. For that to work I think it may be best to drop CanvasItemsGenerator (sequence) as a Spring managed dependency and call the constructor instead. I can make that change in my PR if you agree.

I'm inclined to think that there are only a few instances in which IoC makes sense for the generators.

**Comment by abollini** [comment]
multi-volume (or dspace bundle) will eventually create top level range. I say eventually because if the bundle has not the special `iiif.toc` metadata or there is only one "iiif" bundle it will be just ignored and the result will be similar to your current implementation.

The sequence in the manifest will stay unique as multiple sequences in a IIIF manifest have a different purpose.

**Comment by mspalti** [comment]
Thanks for clarifying, Andrea. I see now that multi-volume is a range (toc) concept and that multiple sequences have a different purpose. 

I very much like your approach to using metadata on the item, bundle and bitstream to configure iiif responses. The implementation looks great to me so far! I ran ITs on your last commit. After fixing a couple tests to match my understanding of expected behavior they all passed with the exception of the `seeAlso` annotation list that has yet to be implemented.  It seems we will need to discuss how to flag `seeAlso `and `rendering` bitstreams (probably using mimetype, metadata, and/or global configuration) when you are ready.

**Comment by abollini** [comment]
hi @mspalti I have completed the refactoring and all test pass on my branch now.
I have added support for metadata at canvas level and tested the hierarchical ranges.
See also and rendering have been also restored.

I have tried to cleanup the code as much as possible adding javadoc and extra comments where useful, I would appreciate if you can double check and make a final cleanup.
If you agree we should merge this in the main branch so to finalize the development within the large PR.

**Pull request merged**
